# Generated by Django 5.0.7 on 2024-10-17 23:54

import apps.kvm.simple_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('transport', models.CharField(choices=[('ssh', 'ssh')], default='ssh', max_length=50)),
                ('driver', models.CharField(choices=[('qemu', 'QEMU'), ('test', 'TEST')], default='qemu', max_length=50)),
                ('port', models.PositiveIntegerField(default=22)),
                ('path', models.CharField(blank=True, default='system', max_length=255, null=True)),
                ('extrac_params', models.CharField(blank=True, help_text='Extra parameters for the URI. Example: "key1=value1,key2=value2"', max_length=255, null=True)),
                ('username', models.CharField(default='anonymous', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Field displayed for preview only.', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.BigIntegerField(blank=True, help_text='Memory size in KiB', null=True)),
                ('vcpus', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_file', models.FileField(max_length=255, upload_to=apps.kvm.simple_models.KeyFile.get_file_path)),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DomainCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='kvm.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=255)),
                ('mgt_ip', models.GenericIPAddressField()),
                ('capabilities_xml', models.TextField(blank=True, null=True)),
                ('capabilities_xml_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('sysinfo_xml', models.TextField(blank=True, null=True)),
                ('sysinfo_xml_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('auth', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kvm.auth')),
                ('tags', models.ManyToManyField(blank=True, to='kvm.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('interface_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_interfaces', to='kvm.hypervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='hypervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='kvm.hypervisor'),
        ),
        migrations.AddField(
            model_name='auth',
            name='key_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvm.keyfile'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('bridge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='kvm.hypervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_filters', to='kvm.hypervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('model_type', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='kvm.domain')),
                ('network_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_interfaces', to='kvm.networkfilter')),
                ('source_network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_interfaces', to='kvm.network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('port_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='kvm.network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_devices', to='kvm.hypervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_devices', to='kvm.domain')),
                ('node_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_domains', to='kvm.nodedevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='kvm.domain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoragePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('pool_type', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.BigIntegerField(blank=True, null=True)),
                ('allocation', models.BigIntegerField(blank=True, null=True)),
                ('available', models.BigIntegerField(blank=True, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_pools', to='kvm.hypervisor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('capacity', models.BigIntegerField(blank=True, null=True)),
                ('allocation', models.BigIntegerField(blank=True, null=True)),
                ('format_type', models.CharField(blank=True, max_length=50, null=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_volumes', to='kvm.domain')),
                ('storage_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='kvm.storagepool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='tags',
            field=models.ManyToManyField(blank=True, to='kvm.tag'),
        ),
    ]
