# Generated by Django 5.0.7 on 2024-10-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='mgt_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
