# Generated by Django 5.0.7 on 2024-09-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('kvm', '0010_alter_xmldata_xml_hash_alter_xmldata_xml_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='passphrase',
        ),
        migrations.RemoveField(
            model_name='auth',
            name='pkey',
        ),
        migrations.AlterField(
            model_name='auth',
            name='extrac_params',
            field=models.CharField(blank=True, help_text='Extra parameters for the URI. Example: "key1=value1,key2=value2"', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='transport',
            field=models.CharField(choices=[('ssh', 'ssh')], default='ssh', max_length=50),
        ),
        migrations.CreateModel(
            name='KeyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('key_file', models.FileField(max_length=255, upload_to='ssh_keys/')),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('instance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='auth',
            name='key_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kvm.keyfile'),
        ),
    ]
