# Generated by Django 5.0.7 on 2024-09-25 18:57

import apps.kvm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0012_remove_keyfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='key_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvm.keyfile'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='password',
            field=models.CharField(blank=True, help_text='Field displayed for preview only.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='auth',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kvm.auth'),
        ),
        migrations.AlterField(
            model_name='keyfile',
            name='key_file',
            field=models.FileField(max_length=255, upload_to=apps.kvm.models.KeyFile.get_file_path),
        ),
    ]
