# Generated by Django 5.0.7 on 2024-10-06 17:04

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0015_hypervisor_arch_hypervisor_microcode_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypervisor',
            name='features',
            field=utils.models.SeparatedCharField(blank=True, help_text="A list of CPU features supported by the host, such as 'vmx:smx:rdrand'. These features can be passed through to KVM guests.", null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='iommu_support',
            field=models.BooleanField(default=False, help_text='Indicates if IOMMU (Input/Output Memory Management Unit) support is enabled. This is essential for device passthrough to VMs, allowing them direct access to hardware.'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='live_migration',
            field=models.BooleanField(default=False, help_text='Indicates if live migration is supported, allowing VMs to be moved between hosts without downtime.'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='pages',
            field=utils.models.SeparatedCharField(blank=True, help_text='Supported memory page sizes (in KiB), such as 4KiB or 2MiB. KVM can use these page sizes to map guest memory more efficiently, affecting memory performance in virtual machines.', null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='suspend_disk',
            field=models.BooleanField(default=False, help_text='Indicates if suspend to disk (S4) is supported, which allows VMs to save their state to disk and resume execution later, even after a power off.'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='suspend_hybrid',
            field=models.BooleanField(default=False, help_text='Indicates if hybrid suspend is supported, combining suspend to memory (S3) and suspend to disk (S4) to allow faster resume while protecting against power loss.'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='suspend_mem',
            field=models.BooleanField(default=False, help_text='Indicates if suspend to memory (S3) is supported, which allows VMs to save their state to memory and resume execution later.'),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='uri_transports',
            field=utils.models.SeparatedCharField(blank=True, help_text='A list of supported URI transport protocols for migration. This defines the network protocols used for live migration of VMs.', null=True),
        ),
    ]
