# Generated by Django 5.0.7 on 2024-10-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0017_hypervisor_cache_banks_hypervisor_secmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hypervisor',
            name='secmodel',
        ),
        migrations.RemoveField(
            model_name='hypervisor',
            name='secmodel_baselabel_types',
        ),
        migrations.RemoveField(
            model_name='hypervisor',
            name='secmodel_baselabels',
        ),
        migrations.RemoveField(
            model_name='hypervisor',
            name='secmodel_doi',
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='secmodels',
            field=models.JSONField(blank=True, help_text="A list of security models supported by the host, such as 'selinux' or 'apparmor'.", null=True),
        ),
    ]
