# Generated by Django 5.0.7 on 2024-10-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('kvm', '0020_alter_vm_cpu_migratable_alter_vm_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='emulator',
            field=models.CharField(blank=True, help_text='The emulator used by the virtual machine.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VMInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=17, null=True)),
                ('static_mac', models.BooleanField(default=False)),
                ('source_network', models.CharField(blank=True, max_length=255, null=True)),
                ('source_dev', models.CharField(blank=True, max_length=255, null=True)),
                ('source_bridge', models.CharField(blank=True, max_length=255, null=True)),
                ('target_dev', models.CharField(blank=True, max_length=255, null=True)),
                ('target_managed', models.BooleanField(default=False)),
                ('model_type', models.CharField(blank=True, max_length=255, null=True)),
                ('if_type', models.CharField(blank=True, max_length=255, null=True)),
                ('apci_index', models.IntegerField(blank=True, null=True)),
                ('instance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.instance')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='kvm.vm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
