# Generated by Django 5.0.7 on 2024-10-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0021_vm_emulator_vminterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminterface',
            name='source_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
