# Generated by Django 5.0.7 on 2024-08-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'instance')},
        ),
    ]
