# Generated by Django 5.0.7 on 2024-08-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_accountgroup_profile_readonly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='readonly',
            new_name='is_readonly',
        ),
    ]
