# Generated by Django 5.0.7 on 2024-08-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='anonymous', max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('pkey', models.CharField(blank=True, max_length=16384, null=True)),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.PositiveIntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hypervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('mgt_ip', models.GenericIPAddressField()),
                ('auth', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kvm.auth')),
                ('tags', models.ManyToManyField(blank=True, to='kvm.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('vcpu', models.PositiveIntegerField(blank=True, null=True)),
                ('memory', models.PositiveIntegerField(blank=True, null=True)),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='kvm.hypervisor')),
                ('tags', models.ManyToManyField(blank=True, to='kvm.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
