# Generated by Django 5.0.7 on 2024-09-08 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0002_auth_instance_hypervisor_instance_tag_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
