# Generated by Django 5.0.7 on 2024-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0003_alter_auth_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='passphrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='pkey',
            field=models.CharField(blank=True, max_length=16384, null=True),
        ),
    ]
