# Generated by Django 5.0.7 on 2024-09-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('kvm', '0003_auth_created_auth_description_auth_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('xml_type', models.CharField(choices=[(None, '(Not selected)'), ('CAPABILITIES', 'Domain capabilities'), ('SMBIOS', 'System Management BIOS (SMBIOS)'), ('OTHER', 'Other XML data')], default='OTHER', max_length=50)),
                ('raw_xml', models.TextField()),
                ('instance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.instance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='xmls',
            field=models.ManyToManyField(blank=True, to='kvm.xmldata'),
        ),
        migrations.AddField(
            model_name='vm',
            name='xmls',
            field=models.ManyToManyField(blank=True, to='kvm.xmldata'),
        ),
    ]
