# Generated by Django 5.0.7 on 2024-08-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0004_alter_auth_passphrase_alter_auth_pkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='username',
            field=models.CharField(default='anonymous', max_length=255),
        ),
    ]
