# Generated by Django 5.0.7 on 2024-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0004_xmldata_hypervisor_xmls_vm_xmls'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='driver',
            field=models.CharField(choices=[('qemu', 'QEMU'), ('test', 'TEST')], default='qemu', max_length=50),
        ),
        migrations.AddField(
            model_name='auth',
            name='extrac_params',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auth',
            name='transport',
            field=models.CharField(choices=[('ssh', 'ssh'), ('libssh', 'libssh'), ('libssh2', 'libssh2'), ('unix', 'unix'), ('ext', 'ext'), ('tcp', 'tcp'), ('tls', 'tls')], default='ssh', max_length=50),
        ),
    ]
