# Generated by Django 5.0.7 on 2024-08-19 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0005_alter_auth_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisor',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvm.auth'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvm.auth'),
        ),
    ]
