# Generated by Django 5.0.7 on 2024-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0005_auth_driver_auth_extrac_params_auth_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
