# Generated by Django 5.0.7 on 2024-08-19 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0006_alter_hypervisor_auth_alter_vm_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='mgt_ip',
        ),
        migrations.AddField(
            model_name='vm',
            name='memory',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vm',
            name='vcpu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hypervisor',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kvm.auth'),
        ),
    ]
