# Generated by Django 5.0.7 on 2024-09-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0006_auth_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmldata',
            name='xml_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
