# Generated by Django 5.0.7 on 2024-09-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0011_remove_auth_passphrase_remove_auth_pkey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyfile',
            name='name',
        ),
    ]
