# Generated by Django 5.0.7 on 2024-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0013_alter_auth_key_file_alter_auth_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypervisor',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='path',
            field=models.CharField(blank=True, default='system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='state',
            field=models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('paused', 'Paused'), ('in shutdown', 'In Shutdown'), ('shut off', 'Shut Off'), ('crashed', 'Crashed'), ('pm suspended', 'PM Suspended'), ('transition', 'Transition'), ('no info', 'No Info')], default='no info', max_length=50),
        ),
        migrations.AlterField(
            model_name='xmldata',
            name='xml_type',
            field=models.CharField(choices=[('Capabilities', 'Domain capabilities'), ('SMBIOS', 'System Management BIOS (SMBIOS)'), ('Domain', 'Domain XML'), ('Other', 'Other XML data')], default='Other', max_length=50),
        ),
    ]
