# Generated by Django 5.0.7 on 2024-10-06 18:55

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvm', '0016_hypervisor_features_hypervisor_iommu_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hypervisor',
            name='cache_banks',
            field=models.JSONField(blank=True, help_text='A list of cache banks for each CPU level. Each entry contains the cache level, type, size, and associated CPUs.', null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='secmodel',
            field=models.CharField(blank=True, help_text='Security model name used by the host.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='secmodel_baselabel_types',
            field=utils.models.SeparatedCharField(blank=True, help_text='Baselabels types', null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='secmodel_baselabels',
            field=utils.models.SeparatedCharField(blank=True, help_text='Baselabels associated with the security model.', null=True),
        ),
        migrations.AddField(
            model_name='hypervisor',
            name='secmodel_doi',
            field=models.CharField(blank=True, help_text='Domain of Interpretation (DOI) for the security model.', max_length=255, null=True),
        ),
    ]
