# Generated by Django 5.0.7 on 2024-08-27 17:57

import django.contrib.sites.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'instances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
