# Generated by Django 5.0.7 on 2024-08-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_profile_created_profile_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='sites',
            new_name='profiles',
        ),
    ]
