
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    volumes:
      # To persist the data beyond the life of the container.
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  #  Cache efficency
  redis:
    restart: always
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: