# Generated by Django 5.0.7 on 2024-10-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_client_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='timezone',
        ),
    ]
