# Generated by Django 5.0.7 on 2024-07-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('Hypervisor', 'VM')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
