# Generated by Django 5.0.7 on 2024-07-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('term', '0002_alter_session_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='enable_console',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='save_output',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('hypervisor', 'vm')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='init', max_length=255),
        ),
    ]
