# Generated by Django 5.0.7 on 2024-08-01 20:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0004_rename_enable_console_session_attach_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='reaonly',
            new_name='readonly',
        ),
    ]
