# Generated by Django 5.0.7 on 2024-08-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0005_alter_session_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='readonly',
            field=models.BooleanField(default=True),
        ),
    ]
