# Generated by Django 5.0.7 on 2024-08-27 17:52

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('init', 'Init'), ('running', 'Running'), ('closed', 'Closed'), ('completed', 'Completed'), ('failed', 'Failed')], default='init', max_length=255)),
                ('output', models.TextField(blank=True, null=True)),
                ('attach', models.BooleanField(default=False)),
                ('readonly', models.BooleanField(default=True)),
                ('saveoutput', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('hypervisor', 'vm')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'index_together': {('content_type', 'object_id')},
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
